### PR TITLE
add driver for lcm162-module (by H. Rasch)

### PR DESCRIPTION
**Pull request by bjo81**
The driver adds support for the lcm162-module which is used in [Nexcom NSA appliances](http://www.nexcom.com/Products/network-and-communication-solutions/mainstream-appliance).

### CODE REVIEW

**Comment by willfe** [comment]
Thanks for submitting this!

**Comment by haraldg** [comment]
@bjo81 While drafting the release notes I noticed that we are missing documentation for this connection type!

**Comment by bjo81** [comment]
I will ask my colleage when he's back from vacation.

**Comment by haraldg** [comment]
On 30.12.2016 20:42, Bjoern Franke wrote:
> I will ask my colleage when he's back from vacation.

Benoit Allard has already submitted minimal documentation
in PR #35 ...

**Pull request merged**
