### PR TITLE
Submitting a patch from the mailing list archive

### PR DESCRIPTION
**Pull request by haraldg**
It seems that Jörg can't be reached (not employed at pyramid.de anymore) so I'm creating this PR for the last patch he submitted to the mailinglist a few month ago.

### CODE REVIEW

**Comment by willfe** [comment]
Looks like this has some conflicts. Anybody want to take a stab at it?

**Comment by haraldg** [comment]
Thats, odd. I did a clean fork from the master branch for this pull request. The only possible merge conflict I can think of, is the ChangeLog. I will update the PR once I'm back at my machine, but in the long run maybe we shouldn't update the ChangeLog from within PRs?

**Comment by willfe** [comment]
Heh! Yeah, maybe we shouldn't update the changelog from PRs.

**Comment by haraldg** [comment]
Ok, so I dropped the update of the change log from this PR. Looks like there are no conflicts now.

**Pull request merged**
