### PR TITLE
Yard2 lcd

### PR DESCRIPTION
**Pull request by YARD2**
Add docu

### CODE REVIEW

**Comment by willfe** [comment]
Does this PR supersede the original one (#17) or is this adding additional changes? I ask just so I know whether I should close the earlier one :)

**Comment by YARD2** [comment]
hopefully all in one. I'm not very familiar with Github

**Comment by willfe** [comment]
Looks good! Thanks for the new driver! I'll get you added to the CREDITS file shortly. Any preference on how your name and/or contact information should appear there?

**Comment by YARD2** [comment]
Credits like in the yard2LCD.c - Thanks

**Comment by willfe** [comment]
Done!

**Pull request merged**
